#!/bin/sh
#
# This tool is used by SliTaz Tiny/Touch Screens desktop.
#
# Copyright (C) 2014 SliTaz ARM - BSD License
# Author: Christophe Lincoln <pankso@slitaz.org>
#

data="/usr/share/slitaz/sts"

case "$1" in
	info)
		if [ "$STS_DESKTOP_WM" ]; then
			echo "STS_DESKTOP_WM : $STS_DESKTOP_WM"
			echo "STS_DESKTOP_ID : $STS_DESKTOP_ID"
		else
			echo "The sts desktop is not running"
		fi ;;
	
	update)
		# Update a user session. Openbox configs are setup by sts-session
		# but on a system update only $data files are updated so users may
		# want to get latest configs.
		rm -rf ${XDG_CONFIG_HOME}/sts
		rm -rf ${XDG_CONFIG_HOME}/lxpanel/sts
		echo "Please logout and login again our STS session" ;;
	
	kill)
		# Close button on panel so we can have undecorated windows
		xid=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)
		pid=$(xprop -id ${xid} _NET_WM_PID | awk '{print $3}')
		kill ${pid} ;;
	
	keyboard)
		# Switch on/of the OSD Keyboard powered by Cellwrite
		if ps | grep -q 'cellwriter --keyboard-only'; then
			cellwriter --hide-window
		else
			cellwriter --keyboard-only --dock-window=2 &
		fi ;;
	
	*|help)
		echo "$(basename $0) [info|kill|keyboard|update]" ;;
esac

exit 0
