#!/bin/sh
#
# Start SliTaz Tiny/Touch Screens desktop session
#

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export STS_DESKTOP_ID="$$"
export STS_DESKTOP_WM="openbox"
export STS_CONFIG_HOME="$XDG_CONFIG_HOME/sts"

data="/usr/share/slitaz/sts"
sts="${XDG_CONFIG_HOME}/sts"

# Ob sts-rc.xml
if [ ! -f "${XDG_CONFIG_HOME}/sts/rc.xml" ]; then
	mkdir -p ${sts}
	cp ${data}/openbox/rc.xml ${sts}
fi

# Ob sts-autostart
if [ ! -x "${XDG_CONFIG_HOME}/sts/autostart" ]; then
	cp ${data}/openbox/autostart ${sts}
	chmod +x ${sts}/autostart
fi

# Tint2 panel 
if [ ! -f "${XDG_CONFIG_HOME}/sts/tint2rc" ]; then
	cp ${data}/tint2/tint2rc ${XDG_CONFIG_HOME}/sts
fi

# LXpanel configs support
if [ -x "/usr/bin/lxpanel" ] && [ ! -d "${XDG_CONFIG_HOME}/lxpanel/sts" ]; then
	cp -rf ${data}/lxpanel ${XDG_CONFIG_HOME}
fi

# Idesk support
if [ -x "/usr/bin/idesk" ] && [ ! -d "${HOME}/.idesktop" ]; then
	mkdir -p ${HOME}/.idesktop
fi

# Start Openbox
exec openbox --config-file ${sts}/rc.xml --startup ${sts}/autostart
